version: "3.2"

services:
## Start the API/WEB server
  ddn-api:
    image: djavorszky/ddn-api:5.2.2
    ports:
      - 7010:7010
    volumes:
      - ./dumps:/ftp
    depends_on:
      - mysql57
    environment:
      DDN_DBADDRESS: mysql57:3306
      DDN_DBUSER: root
      DDN_DBPASS: root
      DDN_DBNAME: ddn
      DDN_MOUNTLOC: /ftp
      DDN_SERVERHOST: ddn-api:7010
      DDN_STARTUPDELAY: 10s
## Start the MySQL 5.7 server. This is needed for the API/WEB server as well.
  mysql57:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql57_db:/var/lib/mysql
# ## Start the agent for the MySQL 5.7 database
  agent-mysql57:
    image: djavorszky/ddn-agent-mysql:5.2.2
    depends_on:
      - mysql57
    environment:
      DDN_VENDOR: mysql 
      DDN_EXEC: /usr/bin/mysql
      DDN_USER: root
      DDN_PASSWORD: root
      DDN_LOCALDBADDR: mysql57:3306
      DDN_REMOTEDBADDR: localhost:3307
      DDN_AGENTADDR: agent-mysql57:7000
      DDN_SHORTNAME: mysql-57
      DDN_MASTERADDRESS: http://ddn-api:7010
      DDN_LOGLEVEL: info
      DDN_STARTUPDELAY: 16s
## Start the MariaDB 10 server.
  mariadb10:
    image: mariadb:10
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb10_db:/var/lib/mysql
## Start the agent for the MariaDB 10 database
  agent-mariadb10:
    image: djavorszky/ddn-agent-mysql:5.2.1
    depends_on:
      - mariadb10
    environment:
      DDN_VENDOR: mariadb
      DDN_EXEC: /usr/bin/mysql
      DDN_USER: root
      DDN_PASSWORD: root
      DDN_LOCALDBADDR: mariadb10:3306
      DDN_REMOTEDBADDR: localhost:3309
      DDN_AGENTADDR: agent-mariadb10:7000
      DDN_SHORTNAME: mariadb-10
      DDN_MASTERADDRESS: http://ddn-api:7010
      DDN_LOGLEVEL: info
      DDN_STARTUPDELAY: 16s
## Start the PostgreSQL 9.4 server.
  postgres94:
    image: postgres:9.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - postgres94_db:/var/lib/postgresql/data
## Start the agent for the PostgreSQL 9.4 database
  agent-postgres94:
    image: djavorszky/ddn-agent-postgres:5.2.2
    depends_on:
      - postgres94
    environment:
      DDN_VENDOR: postgres
      DDN_EXEC: /usr/bin/psql
      DDN_USER: postgres
      DDN_PASSWORD: root
      DDN_LOCALDBADDR: postgres94:5432
      DDN_REMOTEDBADDR: localhost:5432
      DDN_AGENTADDR: agent-postgres94:7000
      DDN_SHORTNAME: postgres-94
      DDN_MASTERADDRESS: http://ddn-api:7010
      DDN_LOGLEVEL: info
      DDN_STARTUPDELAY: 16s


## On first startup, it takes around 70-80 seconds for the oracle
## server to start up. Subsequent startups take about 10 seconds.
## As such, the agent should wait for longer at first start up or
## the whole thing should be restarted once first run is completed.

## Start Oracle 11g server
  oracle11g:
    image: sath89/oracle-xe-11g
    ports:
      - 1521:1521
    volumes:
      - oracle11g_db:/u01/app/oracle
      - oracle_dumps:/dumps
    environment:
      PASS: password
      DEFAULT_SYS_PASS: password
## Start the Oracle 11g agent
  agent-oracle11g:
    image: djavorszky/ddn-agent-oracle:5.2.2
    volumes:
      - oracle_dumps:/dumps
    depends_on:
      - oracle11g
    environment:
      DDN_LOCALDBADDR: oracle11g:1521
      DDN_REMOTEDBADDR: localhost:1521
      DDN_AGENTADDR: agent-oracle11g:7009
      DDN_SHORTNAME: oracle_11g
      DDN_MASTERADDRESS: http://ddn-api:7010
      DDN_USER: system
      DDN_PASSWORD: password
      DDN_SID: xe
      DDN_SYSPASSWORD: password
      DDN_LOGLEVEL: info
      DDN_DATAFILEDIR: /u01/app/oracle/oradata/XE
      DDN_STARTUPDELAY: 11s

# Start the MySQL 5.6 server.
  mysql56:
    image: mysql:5.6
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql56_db:/var/lib/mysql

# Start the agent for the MySQL 5.6 database
  agent-mysql56:
    image: djavorszky/ddn-agent-mysql
    depends_on:
      - mysql56
    environment:
      DDN_VENDOR: mysql
      DDN_EXEC: /usr/bin/mysql
      DDN_USER: root
      DDN_PASSWORD: root
      DDN_LOCALDBADDR: mysql56:3306
      DDN_REMOTEDBADDR: localhost:3308
      DDN_AGENTADDR: agent-mysql56:7000
      DDN_SHORTNAME: mysql-56
      DDN_MASTERADDRESS: http://ddn-api:7010
      DDN_STARTUPDELAY: 10s

volumes:
  mysql57_db:
  mysql56_db:
  mariadb10_db:
  postgres94_db:
  oracle11g_db:
  oracle_dumps:
